apiVersion: v1
kind: Service
metadata:
  name: demo-keda-svc
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: demo-keda

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-keda
spec:
  selector:
    matchLabels:
      app: demo-keda
  template:
    metadata:
      labels:
        app: demo-keda
    spec:
      containers:
      - name: demo-keda
        image: sfelaco/spring-actuator-app
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.2
            memory: 700Mi
          requests:
            cpu: 0.2
            memory: 700Mi
