apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  selector:
    app: {{ template "nginx-two-ports.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginxPorts.httpPort }}
      targetPort: {{ .Values.nginxPorts.httpPort }}
    - name: https
      protocol: TCP
      port: {{ .Values.nginxPorts.httpsPort }}
      targetPort: {{ .Values.nginxPorts.httpsPort }}
