apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: your-image:tag
        ports:
        - name: {{ .Values.service.port1.name }}
          containerPort: {{ .Values.service.port1.targetPort }}
        - name: {{ .Values.service.port2.name }}
          containerPort: {{ .Values.service.port2.targetPort }}