apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: myapp
  ports:
  - name: {{ .Values.service.port1.name }}
    port: {{ .Values.service.port1.port }}
    targetPort: {{ .Values.service.port1.targetPort }}
  - name: {{ .Values.service.port2.name }}
    port: {{ .Values.service.port2.port }}
    targetPort: {{ .Values.service.port2.targetPort }}
